### ISSUE TITLE
Error - v15 -The parameter template['language']['code'] is required.

### ISSUE THREAD

**Issue by turqosoft** [shridarpatil/frappe_whatsapp#54]
Unable to send message using templates. Getting the above error. 
Attaching the generated paylod.

![WAmessagesenderror](https://github.com/shridarpatil/frappe_whatsapp/assets/69414497/ec0c12a7-7879-4906-8ce6-ba691ce221f7)

**Comment by shridarpatil** [comment]
Language code in template is null can you verify that?

**Comment by turqosoft** [comment]
For me the language code is not visible at all during template creation. 
![image](https://github.com/shridarpatil/frappe_whatsapp/assets/69414497/d5011ed6-b063-4486-af07-23fc9d734015)

**Comment by turqosoft** [comment]
How can I use the templates already created in the meta dev site?

**Comment by elbeicktalat** [comment]
Same issue with Arabic
```
Failed to trigger whatsapp message: (#100) The parameter template['language']['code'] is required.
```

I think this is because arabic doesn't countries on ERPNext or even on Meta dev.

**Comment by elbeicktalat** [comment]
Anyway if I put English_US got this error 
```
Failed to trigger whatsapp message: (#132001) Template name does not exist in the translation
```

Not sure why, My templates are enabled on the Meta if there is a way to fetch them it'll be the best thing.

**Comment by elbeicktalat** [comment]
> For me the language code is not visible at all during template creation. 
After save you'll see it

**Comment by elbeicktalat** [comment]
> How can I use the templates already created in the meta dev site?

I got it, you can fetch templates from meta by going to WhatsApp templates then click on 3 dots and then ` Fetch templates from Meta`

<img width="955" alt="image" src="https://github.com/shridarpatil/frappe_whatsapp/assets/59793332/089d2b04-9874-413a-897f-51bcb0674f74">

**Comment by shariquerik** [comment]
It should be fixed please confirm @turqosoft

**Comment by turqosoft** [comment]
It should be. Haven't checked any recent updates though.

**Comment by Riadat-AlMaemura** [comment]
> > How can I use the templates already created in the meta dev site?
> 
> I got it, you can fetch templates from meta by going to WhatsApp templates then click on 3 dots and then ` Fetch templates from Meta`
> 
> <img alt="image" width="955" src="https://private-user-images.githubusercontent.com/59793332/305678269-089d2b04-9874-413a-897f-51bcb0674f74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDYwNTksIm5iZiI6MTcxNDg0NTc1OSwicGF0aCI6Ii81OTc5MzMzMi8zMDU2NzgyNjktMDg5ZDJiMDQtOTg3NC00MTNhLTg5N2YtNTFiY2IwNjc0Zjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE4MDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjE4ODk1YmJmMDViMjVjOTRhOTY1Mjg1YTI4MjliOWU1MDg0YWI2ZDRhODIwNmViY2RkMGEyY2RlYjVlZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9enTjMmlj-kukYn8NxbVM_wJfrISX1o6wtUYp9VUD50">

This is good. I was thinking of creating a code to bring these templates and synchronize them between WhatsApp and erpNext, but the problem remains of deleted templates or templates that delay their authentication by WhatsApp.
